[workspace]
  resolver = "3"
  members = [ "lib", "cli" ]
  default-members = [ "cli" ]

  [workspace.package]
    version = "0.1.0"
    edition = "2024"

  [workspace.dependencies]
    ts-validator-lib.path = "./lib"

    anyhow = "1.0.104"
    clap = { version = "4.6.6", features = ["cargo", "derive"] }
    clap_complete = "4.6.9"
    ovation = "=4.1.0"
    patharg = "0.4.1"
    toml = { version = "0.8.23" }

